/**
 * Built-in PPT templates
 * Each template contains multiple slides with pre-designed elements
 */

// Template 1: Business Blue
const businessBlue = {
  id: 'tpl-business-blue',
  name: 'Business Blue',
  description: 'Clean corporate template with blue accents',
  cover: null, // Will use first slide as cover
  slides: [
    {
      id: 'tpl1-s1',
      background: { type: 'solid', color: '#1a365d' },
      elements: [
        {
          id: 'tpl1-s1-e1',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 0,
          top: 0,
          width: 1000,
          height: 562.5,
          fillColor: '#1a365d',
          opacity: 1,
        },
        {
          id: 'tpl1-s1-e2',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 50,
          top: 380,
          width: 900,
          height: 6,
          fillColor: '#63b3ed',
          opacity: 0.8,
        },
        {
          id: 'tpl1-s1-e3',
          type: 'text',
          content: 'Business Presentation',
          left: 80,
          top: 150,
          width: 840,
          height: 120,
          color: '#ffffff',
          fontSize: 56,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
        {
          id: 'tpl1-s1-e4',
          type: 'text',
          content: 'Your subtitle goes here',
          left: 200,
          top: 300,
          width: 600,
          height: 60,
          color: '#90cdf4',
          fontSize: 24,
          fontWeight: 'normal',
          align: 'center',
          opacity: 1,
        },
      ],
    },
    {
      id: 'tpl1-s2',
      background: { type: 'solid', color: '#ffffff' },
      elements: [
        {
          id: 'tpl1-s2-e1',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 0,
          top: 0,
          width: 1000,
          height: 60,
          fillColor: '#2b6cb0',
          opacity: 1,
        },
        {
          id: 'tpl1-s2-e2',
          type: 'text',
          content: 'Section Title',
          left: 60,
          top: 90,
          width: 880,
          height: 80,
          color: '#1a365d',
          fontSize: 40,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl1-s2-e3',
          type: 'text',
          content:
            '• Key point one\n• Key point two\n• Key point three\n• Key point four',
          left: 60,
          top: 200,
          width: 880,
          height: 300,
          color: '#2d3748',
          fontSize: 22,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
      ],
    },
    {
      id: 'tpl1-s3',
      background: { type: 'solid', color: '#f7fafc' },
      elements: [
        {
          id: 'tpl1-s3-e1',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 0,
          top: 0,
          width: 6,
          height: 562.5,
          fillColor: '#2b6cb0',
          opacity: 1,
        },
        {
          id: 'tpl1-s3-e2',
          type: 'text',
          content: 'Two Column Layout',
          left: 40,
          top: 30,
          width: 920,
          height: 60,
          color: '#1a365d',
          fontSize: 32,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl1-s3-e3',
          type: 'text',
          content:
            'Left column content goes here. Add your key insights and data.',
          left: 40,
          top: 120,
          width: 440,
          height: 380,
          color: '#4a5568',
          fontSize: 18,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl1-s3-e4',
          type: 'text',
          content:
            'Right column content goes here. Support your argument with evidence.',
          left: 520,
          top: 120,
          width: 440,
          height: 380,
          color: '#4a5568',
          fontSize: 18,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
      ],
    },
  ],
}

// Template 2: Modern Gradient
const modernGradient = {
  id: 'tpl-modern-gradient',
  name: 'Modern Gradient',
  description: 'Contemporary design with gradient backgrounds',
  cover: null,
  slides: [
    {
      id: 'tpl2-s1',
      background: { type: 'solid', color: '#667eea' },
      elements: [
        {
          id: 'tpl2-s1-e1',
          type: 'shape',
          svgPath:
            'M0,100 C150,0 350,200 500,100 C650,0 850,200 1000,100 L1000,600 L0,600 Z',
          viewBox: [1000, 600],
          left: 0,
          top: 0,
          width: 1000,
          height: 562.5,
          fillColor: '#764ba2',
          opacity: 0.4,
        },
        {
          id: 'tpl2-s1-e2',
          type: 'text',
          content: 'Creative Ideas',
          left: 100,
          top: 140,
          width: 800,
          height: 120,
          color: '#ffffff',
          fontSize: 64,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
        {
          id: 'tpl2-s1-e3',
          type: 'text',
          content: 'Innovation meets design',
          left: 200,
          top: 300,
          width: 600,
          height: 50,
          color: '#e2e8f0',
          fontSize: 22,
          fontWeight: 'normal',
          align: 'center',
          opacity: 1,
        },
      ],
    },
    {
      id: 'tpl2-s2',
      background: { type: 'solid', color: '#fafafa' },
      elements: [
        {
          id: 'tpl2-s2-e1',
          type: 'shape',
          svgPath: 'M0,0 C100,50 200,0 300,30 C400,60 500,0 600,40 L600,0 Z',
          viewBox: [600, 60],
          left: 0,
          top: 0,
          width: 1000,
          height: 80,
          fillColor: '#667eea',
          opacity: 1,
        },
        {
          id: 'tpl2-s2-e2',
          type: 'text',
          content: 'Our Approach',
          left: 60,
          top: 100,
          width: 880,
          height: 70,
          color: '#2d3748',
          fontSize: 36,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl2-s2-e3',
          type: 'shape',
          svgPath: 'M100,0 A100,100 0 1,1 100,200 A100,100 0 1,1 100,0 Z',
          viewBox: [200, 200],
          left: 80,
          top: 200,
          width: 120,
          height: 120,
          fillColor: '#667eea',
          opacity: 1,
        },
        {
          id: 'tpl2-s2-e4',
          type: 'shape',
          svgPath: 'M100,0 A100,100 0 1,1 100,200 A100,100 0 1,1 100,0 Z',
          viewBox: [200, 200],
          left: 300,
          top: 200,
          width: 120,
          height: 120,
          fillColor: '#764ba2',
          opacity: 1,
        },
        {
          id: 'tpl2-s2-e5',
          type: 'shape',
          svgPath: 'M100,0 A100,100 0 1,1 100,200 A100,100 0 1,1 100,0 Z',
          viewBox: [200, 200],
          left: 520,
          top: 200,
          width: 120,
          height: 120,
          fillColor: '#f093fb',
          opacity: 1,
        },
        {
          id: 'tpl2-s2-e6',
          type: 'text',
          content: 'Research',
          left: 80,
          top: 340,
          width: 120,
          height: 40,
          color: '#4a5568',
          fontSize: 14,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
        {
          id: 'tpl2-s2-e7',
          type: 'text',
          content: 'Design',
          left: 300,
          top: 340,
          width: 120,
          height: 40,
          color: '#4a5568',
          fontSize: 14,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
        {
          id: 'tpl2-s2-e8',
          type: 'text',
          content: 'Deliver',
          left: 520,
          top: 340,
          width: 120,
          height: 40,
          color: '#4a5568',
          fontSize: 14,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
      ],
    },
    {
      id: 'tpl2-s3',
      background: { type: 'solid', color: '#2d3748' },
      elements: [
        {
          id: 'tpl2-s3-e1',
          type: 'text',
          content: 'Thank You',
          left: 200,
          top: 180,
          width: 600,
          height: 100,
          color: '#ffffff',
          fontSize: 56,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
        {
          id: 'tpl2-s3-e2',
          type: 'text',
          content: 'Contact: your@email.com',
          left: 250,
          top: 320,
          width: 500,
          height: 40,
          color: '#a0aec0',
          fontSize: 20,
          fontWeight: 'normal',
          align: 'center',
          opacity: 1,
        },
      ],
    },
  ],
}

// Template 3: Minimal Dark
const minimalDark = {
  id: 'tpl-minimal-dark',
  name: 'Minimal Dark',
  description: 'Elegant dark theme with minimal elements',
  cover: null,
  slides: [
    {
      id: 'tpl3-s1',
      background: { type: 'solid', color: '#1a1a2e' },
      elements: [
        {
          id: 'tpl3-s1-e1',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 60,
          top: 220,
          width: 80,
          height: 4,
          fillColor: '#e94560',
          opacity: 1,
        },
        {
          id: 'tpl3-s1-e2',
          type: 'text',
          content: 'DARK\nMODE',
          left: 60,
          top: 120,
          width: 500,
          height: 180,
          color: '#ffffff',
          fontSize: 72,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl3-s1-e3',
          type: 'text',
          content: 'Presentation Template',
          left: 60,
          top: 340,
          width: 400,
          height: 40,
          color: '#718096',
          fontSize: 18,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
      ],
    },
    {
      id: 'tpl3-s2',
      background: { type: 'solid', color: '#16213e' },
      elements: [
        {
          id: 'tpl3-s2-e1',
          type: 'text',
          content: 'Key Features',
          left: 60,
          top: 40,
          width: 400,
          height: 60,
          color: '#e94560',
          fontSize: 32,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl3-s2-e2',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 60,
          top: 130,
          width: 400,
          height: 160,
          fillColor: '#0f3460',
          opacity: 1,
        },
        {
          id: 'tpl3-s2-e3',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 520,
          top: 130,
          width: 400,
          height: 160,
          fillColor: '#0f3460',
          opacity: 1,
        },
        {
          id: 'tpl3-s2-e4',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 60,
          top: 330,
          width: 400,
          height: 160,
          fillColor: '#0f3460',
          opacity: 1,
        },
        {
          id: 'tpl3-s2-e5',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 520,
          top: 330,
          width: 400,
          height: 160,
          fillColor: '#0f3460',
          opacity: 1,
        },
        {
          id: 'tpl3-s2-e6',
          type: 'text',
          content: 'Feature 1\nDescription here',
          left: 80,
          top: 150,
          width: 360,
          height: 120,
          color: '#e2e8f0',
          fontSize: 16,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl3-s2-e7',
          type: 'text',
          content: 'Feature 2\nDescription here',
          left: 540,
          top: 150,
          width: 360,
          height: 120,
          color: '#e2e8f0',
          fontSize: 16,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl3-s2-e8',
          type: 'text',
          content: 'Feature 3\nDescription here',
          left: 80,
          top: 350,
          width: 360,
          height: 120,
          color: '#e2e8f0',
          fontSize: 16,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl3-s2-e9',
          type: 'text',
          content: 'Feature 4\nDescription here',
          left: 540,
          top: 350,
          width: 360,
          height: 120,
          color: '#e2e8f0',
          fontSize: 16,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
      ],
    },
  ],
}

// Template 4: Education Green
const educationGreen = {
  id: 'tpl-education-green',
  name: 'Education',
  description: 'Fresh green theme for educational presentations',
  cover: null,
  slides: [
    {
      id: 'tpl4-s1',
      background: { type: 'solid', color: '#f0fff4' },
      elements: [
        {
          id: 'tpl4-s1-e1',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 0,
          top: 0,
          width: 350,
          height: 562.5,
          fillColor: '#276749',
          opacity: 1,
        },
        {
          id: 'tpl4-s1-e2',
          type: 'text',
          content: 'Learning\nObjectives',
          left: 30,
          top: 150,
          width: 300,
          height: 200,
          color: '#ffffff',
          fontSize: 42,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl4-s1-e3',
          type: 'text',
          content: 'Course name or topic goes here.\nDate: 2024',
          left: 400,
          top: 200,
          width: 540,
          height: 120,
          color: '#2d3748',
          fontSize: 22,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
      ],
    },
    {
      id: 'tpl4-s2',
      background: { type: 'solid', color: '#ffffff' },
      elements: [
        {
          id: 'tpl4-s2-e1',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 0,
          top: 0,
          width: 1000,
          height: 8,
          fillColor: '#38a169',
          opacity: 1,
        },
        {
          id: 'tpl4-s2-e2',
          type: 'text',
          content: 'Agenda',
          left: 60,
          top: 40,
          width: 880,
          height: 60,
          color: '#276749',
          fontSize: 36,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl4-s2-e3',
          type: 'text',
          content:
            '1. Introduction & Overview\n2. Core Concepts\n3. Practical Examples\n4. Hands-on Exercise\n5. Q&A Session',
          left: 60,
          top: 130,
          width: 880,
          height: 380,
          color: '#2d3748',
          fontSize: 22,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
      ],
    },
    {
      id: 'tpl4-s3',
      background: { type: 'solid', color: '#ffffff' },
      elements: [
        {
          id: 'tpl4-s3-e1',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 0,
          top: 0,
          width: 1000,
          height: 8,
          fillColor: '#38a169',
          opacity: 1,
        },
        {
          id: 'tpl4-s3-e2',
          type: 'text',
          content: 'Key Concept',
          left: 60,
          top: 40,
          width: 500,
          height: 60,
          color: '#276749',
          fontSize: 36,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl4-s3-e3',
          type: 'text',
          content:
            'Explanation of the main concept goes here. Use simple language and clear examples to help students understand.',
          left: 60,
          top: 130,
          width: 550,
          height: 200,
          color: '#4a5568',
          fontSize: 18,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl4-s3-e4',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 640,
          top: 100,
          width: 320,
          height: 320,
          fillColor: '#c6f6d5',
          opacity: 1,
        },
        {
          id: 'tpl4-s3-e5',
          type: 'text',
          content: 'Diagram or\nImage here',
          left: 700,
          top: 220,
          width: 200,
          height: 80,
          color: '#276749',
          fontSize: 16,
          fontWeight: 'normal',
          align: 'center',
          opacity: 1,
        },
      ],
    },
  ],
}

// Template 5: Data Report
const dataReport = {
  id: 'tpl-data-report',
  name: 'Data Report',
  description: 'Professional data-driven presentation template',
  cover: null,
  slides: [
    {
      id: 'tpl5-s1',
      background: { type: 'solid', color: '#ffffff' },
      elements: [
        {
          id: 'tpl5-s1-e1',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 0,
          top: 0,
          width: 1000,
          height: 200,
          fillColor: '#2c5282',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e2',
          type: 'text',
          content: 'Quarterly Report',
          left: 60,
          top: 50,
          width: 600,
          height: 80,
          color: '#ffffff',
          fontSize: 44,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e3',
          type: 'text',
          content: 'Q4 2024 Performance Overview',
          left: 60,
          top: 130,
          width: 600,
          height: 40,
          color: '#bee3f8',
          fontSize: 18,
          fontWeight: 'normal',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e4',
          type: 'text',
          content: 'Key Metrics Summary',
          left: 60,
          top: 240,
          width: 880,
          height: 50,
          color: '#2d3748',
          fontSize: 24,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e5',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 60,
          top: 310,
          width: 200,
          height: 200,
          fillColor: '#ebf8ff',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e6',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 290,
          top: 310,
          width: 200,
          height: 200,
          fillColor: '#ebf8ff',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e7',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 520,
          top: 310,
          width: 200,
          height: 200,
          fillColor: '#ebf8ff',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e8',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 750,
          top: 310,
          width: 200,
          height: 200,
          fillColor: '#ebf8ff',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e9',
          type: 'text',
          content: '128K\nUsers',
          left: 60,
          top: 360,
          width: 200,
          height: 80,
          color: '#2c5282',
          fontSize: 22,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e10',
          type: 'text',
          content: '45%\nGrowth',
          left: 290,
          top: 360,
          width: 200,
          height: 80,
          color: '#2c5282',
          fontSize: 22,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e11',
          type: 'text',
          content: '$2.4M\nRevenue',
          left: 520,
          top: 360,
          width: 200,
          height: 80,
          color: '#2c5282',
          fontSize: 22,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
        {
          id: 'tpl5-s1-e12',
          type: 'text',
          content: '98%\nSatisfaction',
          left: 750,
          top: 360,
          width: 200,
          height: 80,
          color: '#2c5282',
          fontSize: 22,
          fontWeight: 'bold',
          align: 'center',
          opacity: 1,
        },
      ],
    },
    {
      id: 'tpl5-s2',
      background: { type: 'solid', color: '#ffffff' },
      elements: [
        {
          id: 'tpl5-s2-e1',
          type: 'shape',
          svgPath: 'M0,0 L200,0 L200,200 L0,200 Z',
          viewBox: [200, 200],
          left: 0,
          top: 0,
          width: 1000,
          height: 6,
          fillColor: '#2c5282',
          opacity: 1,
        },
        {
          id: 'tpl5-s2-e2',
          type: 'text',
          content: 'Detailed Analysis',
          left: 60,
          top: 30,
          width: 600,
          height: 60,
          color: '#2c5282',
          fontSize: 32,
          fontWeight: 'bold',
          align: 'left',
          opacity: 1,
        },
        {
          id: 'tpl5-s2-e3',
          type: 'table',
          left: 60,
          top: 110,
          width: 880,
          height: 400,
          opacity: 1,
          theme: { color: '#2c5282' },
          colWidths: [0.25, 0.25, 0.25, 0.25],
          data: [
            [
              { id: 'c1', text: 'Metric', style: { bold: true } },
              { id: 'c2', text: 'Q1', style: { bold: true } },
              { id: 'c3', text: 'Q2', style: { bold: true } },
              { id: 'c4', text: 'Q3', style: { bold: true } },
            ],
            [
              { id: 'c5', text: 'Revenue', style: {} },
              { id: 'c6', text: '$1.2M', style: {} },
              { id: 'c7', text: '$1.8M', style: {} },
              { id: 'c8', text: '$2.4M', style: {} },
            ],
            [
              { id: 'c9', text: 'Users', style: {} },
              { id: 'c10', text: '80K', style: {} },
              { id: 'c11', text: '105K', style: {} },
              { id: 'c12', text: '128K', style: {} },
            ],
            [
              { id: 'c13', text: 'NPS', style: {} },
              { id: 'c14', text: '72', style: {} },
              { id: 'c15', text: '85', style: {} },
              { id: 'c16', text: '92', style: {} },
            ],
          ],
        },
      ],
    },
  ],
}

export const TEMPLATE_LIST = [
  businessBlue,
  modernGradient,
  minimalDark,
  educationGreen,
  dataReport,
]
